version: '3.8'

services:
  mysql:
    image: mysql/mysql-server:8.0
    container_name: dev-food-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: food_db
      MYSQL_USER: host
      MYSQL_PASSWORD: host
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d/
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

volumes:
  mysql_data:
